### ISSUE TITLE
docs: improvements to the release checklist

### ISSUE THREAD

**Issue by safl** [xnvme/xnvme#382]
On https://github.com/OpenMPDK/xNVMe/pull/380 documentation of the xNVMe release process is added. It has a couple of items which are post-poned for integration, the areas of improvement are:

- [x] How to publish the xNVMe Rust crate (xnvme-sys)
- [ ] How to publish the xNVMe package (xnvme)

**Comment by karlowich** [comment]
This has been addressed in #384

**Comment by karlowich** [comment]
This is available here: 
https://xnvme.io/contributing/release-checklist.html

Thus closing this
